apiVersion: v1
kind: Secret
metadata:
  name: citizen-service-secret
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Host=postgres;Database=citizenservice;Username=postgres;******"
  Oidc__ClientSecret: "CHANGE_ME"
