apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "citizen-service.fullname" . }}-api
  labels:
    {{- include "citizen-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "citizen-service.api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "citizen-service.api.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
      {{- with .Values.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ default (include "citizen-service.fullname" .) .Values.serviceAccount.name }}
      {{- end }}
      containers:
        - name: api
          image: {{ include "citizen-service.api.image" . }}
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.api.service.targetPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "citizen-service.fullname" . }}-config
            - secretRef:
                name: {{ include "citizen-service.secretName" . }}
          {{- if .Values.api.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.api.readinessProbe.path }}
              port: {{ .Values.api.service.targetPort }}
            initialDelaySeconds: {{ .Values.api.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.readinessProbe.periodSeconds }}
          {{- end }}
          {{- with .Values.api.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
