apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "citizen-service.fullname" . }}-config
  labels:
    {{- include "citizen-service.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.config.aspnetcoreEnvironment | quote }}
  Jwt__Authority: {{ .Values.config.jwtAuthority | quote }}
  Jwt__Audience: {{ .Values.config.jwtAudience | quote }}
  PersonRegistry__BaseUrl: {{ .Values.config.personRegistryBaseUrl | quote }}
  CitizenApi__BaseUrl: {{ .Values.config.citizenApiBaseUrl | quote }}
  Oidc__Authority: {{ .Values.config.oidcAuthority | quote }}
  Oidc__ClientId: {{ .Values.config.oidcClientId | quote }}
