{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "citizen-service.fullname" . }}-secret
  labels:
    {{- include "citizen-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: {{ .Values.secret.connectionString | quote }}
  Oidc__ClientSecret: {{ .Values.secret.oidcClientSecret | quote }}
{{- end }}
