apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "citizen-service.fullname" . }}-web
  labels:
    {{- include "citizen-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "citizen-service.web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "citizen-service.web.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
      {{- with .Values.web.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ default (include "citizen-service.fullname" .) .Values.serviceAccount.name }}
      {{- end }}
      containers:
        - name: web
          image: {{ include "citizen-service.web.image" . }}
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.web.service.targetPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "citizen-service.fullname" . }}-config
            - secretRef:
                name: {{ include "citizen-service.secretName" . }}
          {{- with .Values.web.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
